[msg TestMSG [Baku]]
[bup 0 207 102 0 0]Lemme get uhh...[n]
[clr 9]BONELESS PIZZA[clr 0] with a 2 liter of coke.[w][e]

[sel TestSelect]
Are you a dumbass?[e]
WTF?![e]
You gotta be high as shit.[e]

[msg res1 [Baku]]
[bup 0 207 102 0 0]Fuck you mean B?[n]
Aight, look, lemme get that pizza [clr 9]BONELESS[clr 0].[w][e]

[msg res2 [Baku]]
[bup 0 207 102 0 0]TF did I just say then?[n][w][e]

[sel bone2]
You said, "Lemme get it boneless."[e]
As if pizza got a damn bone on it.[e]

[msg res3 [Baku]]
[bup 0 207 102 0 0][clr 9]Y'all got bones in ya shit then?[clr 0][n][w][e]

[sel nah]
Nah.[e]

[msg res4 [Baku]]
[bup 0 207 102 0 0]So whats the problem?[n][w][e]

[sel bone4]
I wish I never got into food service.[e]
DICK HEAD.[e]

[msg res5 [Baku]]
[bup 0 207 102 0 0][clr 9]Just don't put those shits in my pizza bruh,[clr 0][n]
how many times I gotta say it!?[w][e]

[sel bone5]
Explain your fucked up logic.[e]
You better shut that shit, or you aint gettin this pizza.[e]

[msg res6 [Baku]]
[bup 0 207 102 0 0]If it ain't got no bone in it, iss [clr 9]BONELESS[clr 0].[n][w][e]

[sel bone6]
What school you go to?[e]
You a elementary drop-out or what?[e]

[msg res7 [Baku]]
[bup 0 207 102 0 0][clr 9]JUST MAKE MY SHIT BONELESS, DEADASS![clr 0][n][w][e]

[sel bone7]
I am deadass not making this pizza.[e]
Do not call this restaurant ever again.[e]

[sel bone1]
Like I said, are you stupid?[e]
Uhh... pizza dont got bone on it.[e]